configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/glint.yaml # envgs model configuration
    - configs/datasets/manual_synthetic/scene_2.yaml # dataset usage configuration

model_cfg:
    sampler_cfg:
        trans_env_densify_grad_threshold: 0.0002
    supervisor_cfg:
        perc_loss_start_iter: 45000 # less iterations for faster training

dataloader_cfg: &dataloader_cfg
    dataset_cfg: &dataset_cfg
        n_rays: -1
        use_normals: False # use monocular normal prior
        use_sky_masks: False # use sky masks
        use_diffren: False # use diffusionrenderer priors
        
runner_cfg:
    epochs: 120

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
