configs:
    - configs/base.yaml
    - configs/models/glint.yaml
    - configs/datasets/3d-front-t/scene_1.yaml

model_cfg:
    sampler_cfg:
        trans_env_densify_grad_threshold: 0.0002
    supervisor_cfg:
        use_normal_type: "diffren"
        perc_loss_start_iter: 45000

runner_cfg:
    epochs: 120
