configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/glint.yaml # envgs model configuration
    - configs/datasets/ref-dl3dv/10dc690f346eac9a3fddaa6a29cd8707506bd6898edf06b3e46768ecf59c07c3.yaml # dataset usage configuration

model_cfg:
    supervisor_cfg:
        perc_loss_start_iter: 45000 # less iterations for faster training

dataloader_cfg: &dataloader_cfg
    dataset_cfg: &dataset_cfg
        use_sky_masks: True # use sky masks

runner_cfg:
    epochs: 120

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
