configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/glint.yaml # envgs model configuration
    - configs/datasets/ref-dl3dv/52410f0264d14bde6acd695c637aaa274833be8afcf05ef4fd6a51176ad2dbd2.yaml # dataset usage configuration

model_cfg:
    supervisor_cfg:
        perc_loss_start_iter: 45000 # less iterations for faster training

runner_cfg:
    epochs: 120

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
