configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/glint.yaml # envgs model configuration
    - configs/datasets/ref-dl3dv/b62621fa51c1f50589006db5b6c8f13d13249998b639aa7cd44f07c2d2e897ce.yaml # dataset usage configuration

model_cfg:
    supervisor_cfg:
        perc_loss_start_iter: 45000 # less iterations for faster training

runner_cfg:
    epochs: 120

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
