configs:
    - configs/base.yaml
    - configs/models/glint.yaml
    - configs/datasets/ref-dl3dv/3712b8fdcb94128c92c2e2c30fb529851e3231cdc7c4451bc6c784f923386e93.yaml

model_cfg:
    supervisor_cfg:
        perc_loss_start_iter: 45000

runner_cfg:
    epochs: 120
