configs:
    - configs/base.yaml
    - configs/models/glint.yaml
    - configs/datasets/ref-dl3dv/52410f0264d14bde6acd695c637aaa274833be8afcf05ef4fd6a51176ad2dbd2.yaml

model_cfg:
    supervisor_cfg:
        perc_loss_start_iter: 45000

runner_cfg:
    epochs: 120
