configs:
    - configs/base.yaml
    - configs/models/glint.yaml
    - configs/datasets/ref-dl3dv/543b6607de9318e3a0c68b267a4b616fdc5849a140ba184807d5e70e567f8ec0.yaml

model_cfg:
    supervisor_cfg:
        perc_loss_start_iter: 45000

runner_cfg:
    epochs: 120
