configs:
    - configs/base.yaml
    - configs/models/glint.yaml
    - configs/datasets/ref-dl3dv/b65e86833c1ae29714ce881bb9d14d3ed1256a08ab944fd9e75d6b29c674346d.yaml

model_cfg:
    supervisor_cfg:
        perc_loss_start_iter: 45000

runner_cfg:
    epochs: 120
