configs:
    - configs/base.yaml
    - configs/models/glint.yaml
    - configs/datasets/ref-dl3dv/b9df30d6e6078880acc88acb01872c65d337f84b9dba44a23fa29c9861d7e23b.yaml

model_cfg:
    supervisor_cfg:
        perc_loss_start_iter: 45000
        basecolor_threshold: 0.2
        depth_discrepancy_threshold: 0.001
runner_cfg:
    epochs: 120
