
inference_model_weights: '/mnt/nas3/youngju/glint/checkpoints'

inference_res: [ 512, 512 ]

inference_input_dir: "examples/input_video_frames/"
inference_save_dir: "examples/output_delighting/"

inference_n_frames: 24
overlap_n_frames: 6
inference_n_steps: 20
inference_min_guidance_scale: 1.0
inference_max_guidance_scale: 1.0
#inference_n_repeat: 1

model_dtype: fp16
decode_chunk_size: 8
cond_mode: 'skip' # clip branch for cross attention
chunk_mode: 'all' # first, all, drop_last
image_group_mode: "custom"  # folder, webdataset

model_passes:
  - "basecolor"
  - "metallic"
  - "roughness"
  - "normal"
  - "depth"
  - "diffuse_albedo" 

seed: 0
save_video: true
save_video_fps: 10
save_image: true

autocast: true

use_deterministic_mode: false

subsample_every_n_frames: 1
